// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQH2enLG_FKRYnrWwbwXNrkYT-fosOZY',
    appId: '1:203230345290:web:111b997ec462902ff5ceb3',
    messagingSenderId: '203230345290',
    projectId: 'chatapp-d8bac',
    authDomain: 'chatapp-d8bac.firebaseapp.com',
    storageBucket: 'chatapp-d8bac.firebasestorage.app',
    measurementId: 'G-X9J626XLK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp3t34tsFLOjefApC-tkDJnBEMPrfmppA',
    appId: '1:203230345290:android:db4aa243a3c6b6a4f5ceb3',
    messagingSenderId: '203230345290',
    projectId: 'chatapp-d8bac',
    storageBucket: 'chatapp-d8bac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiIA-psW49pGrX7Hbvl8RiohOGwHOF2_4',
    appId: '1:203230345290:ios:06610918f39e8db4f5ceb3',
    messagingSenderId: '203230345290',
    projectId: 'chatapp-d8bac',
    storageBucket: 'chatapp-d8bac.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiIA-psW49pGrX7Hbvl8RiohOGwHOF2_4',
    appId: '1:203230345290:ios:06610918f39e8db4f5ceb3',
    messagingSenderId: '203230345290',
    projectId: 'chatapp-d8bac',
    storageBucket: 'chatapp-d8bac.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHQH2enLG_FKRYnrWwbwXNrkYT-fosOZY',
    appId: '1:203230345290:web:a62ae2bbae087dc0f5ceb3',
    messagingSenderId: '203230345290',
    projectId: 'chatapp-d8bac',
    authDomain: 'chatapp-d8bac.firebaseapp.com',
    storageBucket: 'chatapp-d8bac.firebasestorage.app',
    measurementId: 'G-TXDJ3DQ66W',
  );
}
